site: "Orange Appeal: Syracuse University's Original All-Male A Cappella Group"
baseurl: "orangeappeal_jekyll"
url: orangeappeal.net
permalink: ""
collections:
  - posts
  - guys
plugins:
  - jekyll-sitemap
