site: "Orange Appeal: Syracuse University's Original All-Male A Cappella Group"
baseurl: "orangeappeal_jekyll"
url: https://joshuafayer.com/
permalink: /:title/
collections:
  - posts
  - guys
plugins:
  - jekyll-sitemap
